# Generated by Django 5.2.4 on 2025-10-30 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Subscriber's email address", max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the user subscribed')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the email has been verified')),
                ('verification_code', models.CharField(blank=True, help_text='6-digit verification code', max_length=6, null=True)),
                ('code_expires_at', models.DateTimeField(blank=True, help_text='When the verification code expires', null=True)),
                ('verification_attempts', models.PositiveIntegerField(default=0, help_text='Number of verification attempts')),
            ],
            options={
                'verbose_name': 'Email Subscription',
                'verbose_name_plural': 'Email Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
